spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    url: >-
      jdbc:oracle:thin:@(DESCRIPTION=
        (ADDRESS_LIST=
          (ADDRESS=(PROTOCOL=TCP)(HOST=${DB_HOST})(PORT=${DB_PORT}))
          (ADDRESS=(PROTOCOL=TCP)(HOST=${STDB_HOST})(PORT=${DB_PORT}))
        )
        (CONNECT_DATA=(SERVICE_NAME=${DB_NAME}))
        (FAILOVER=on)(LOAD_BALANCE=off)
      )
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
  mvc:
    hiddenmethod:
      filter:
        enabled: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

aws:
  cognito:
    user-pool-id: ${COGNITO_USER_POOL_ID}